server:
  port: 8081

spring:
  application:
    name: order-processing-service

payment:
  service:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
