apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-investment-service
  labels:
    app: investment-service
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: investment-service
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: investment-service
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: investment-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
