apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-processing-service
  labels:
    app: order-processing-service
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-processing-service
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: order-processing-service
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: order-processing-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: PAYMENT_SERVICE_URL
              value: {{ .Values.env.PAYMENT_SERVICE_URL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
